### ISSUE TITLE
[FEAT] Server 클래스 구현

### ISSUE THREAD

**Issue by jiyuneel** [falconlee236/IRC_Server#10]
- Server 클래스를 구현하여 main 함수의 로직을 정리합니다.

**Comment by falconlee236** [comment]
* 소캣 바인딩 + 소캣설정
* 새로운 클라이언트 들어왔을때 연결설정
* 클라이언트 read요청 들어올때 연결설정

크게 3가지 나누면 좋을것 같습니다~
